name: Run Automation Tests

on:
  repository_dispatch:
    types: [run-tests]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install Allure CLI
        run: npm install -g allure-commandline

      - name: Clean previous allure results and report
        run: |
          rm -rf allure-results
          rm -rf allure-report

      - name: Full clean gh-pages
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"

          git clone --branch gh-pages https://github.com/suryana-code/MyPortfolio-CICD.git gh-pages-temp || true
          cd gh-pages-temp

          # Coba hapus semua file jika ada, lanjut meskipun kosong
          rm -rf * || true
          rm -rf .[^.]* || true # hapus dotfiles seperti .nojekyll kalau ada

          touch .gitignore
          echo "# cleaned" > .gitignore

          git add .
          git commit -m "Clean old allure report" || echo "Nothing to commit"
          git push origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}

      - name: Run tests
        run: npm run wdio

      - name: Generate Allure Report
        run: |
          allure generate allure-results --clean -o allure-report

      - name: Deploy Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./allure-report
          publish_branch: gh-pages
