name: Run Automation Tests

on:
  repository_dispatch:
    types: [run-tests]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install Allure CLI
        run: npm install -g allure-commandline

      - name: Clean previous allure results and report
        run: |
          npm run clearAllure-Result
          npm run clearAllure-Report

      - name: Run tests
        run: npm run wdio

      - name: Generate Allure Report
        run: |
          npm run report:generate

      - name: Clean history so old data doesn't appear
        run: rm -rf allure-report/history

      - name: Deploy Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./allure-report
          publish_branch: gh-pages
          keep_files: false
